//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQLServerUtils {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SQLServerUtils.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (function(e){function t(t){for(var a,i,o=t[0],c=t[1],l=t[2],d=0,v=[];d&lt;o.length;d++)i=o[d],Object.prototype.hasOwnProperty.call(s,i)&amp;&amp;s[i]&amp;&amp;v.push(s[i][0]),s[i]=0;for(a in c)Object.prototype.hasOwnProperty.call(c,a)&amp;&amp;(e[a]=c[a]);u&amp;&amp;u(t);while(v.length)v.shift()();return n.push.apply(n,l||[]),r()}function r(){for(var e,t=0;t&lt;n.length;t++){for(var r=n[t],a=!0,o=1;o&lt;r.length;o++){var c=r[o];0!==s[c]&amp;&amp;(a=!1)}a&amp;&amp;(n.splice(t--,1),e=i(i.s=r[0]))}return e}var a={},s={app:0},n=[];function i(t){if(a[t])return a[t].ex [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string app_js {
            get {
                return ResourceManager.GetString("app_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;version&quot;:3,&quot;sources&quot;:[&quot;webpack:///webpack/bootstrap&quot;,&quot;webpack:///./src/App.vue?f870&quot;,&quot;webpack:///./src/App.vue?d49c&quot;,&quot;webpack:///./src/components/SqlMain.vue?f233&quot;,&quot;webpack:///src/components/SqlMain.vue&quot;,&quot;webpack:///./src/components/SqlMain.vue?ecc7&quot;,&quot;webpack:///./src/components/SqlMain.vue?ee5d&quot;,&quot;webpack:///src/App.vue&quot;,&quot;webpack:///./src/App.vue?4b00&quot;,&quot;webpack:///./src/App.vue?bff9&quot;,&quot;webpack:///./src/main.js&quot;,&quot;webpack:///./src/components/SqlMain.vue?7c44&quot;],&quot;names&quot;:[&quot;webpackJsonpCallback&quot;,&quot;data&quot;,&quot;moduleId [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string app_map {
            get {
                return ResourceManager.GetString("app_map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Source={0};Initial Catalog={1};Integrated Security=True.
        /// </summary>
        internal static string connectionStringTemplate {
            get {
                return ResourceManager.GetString("connectionStringTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon favicon {
            get {
                object obj = ResourceManager.GetObject("favicon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=en&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=utf-8&gt;
        ///    &lt;meta http-equiv=X-UA-Compatible content=&quot;IE=edge&quot;&gt;
        ///    &lt;meta name=viewport content=&quot;width=device-width,initial-scale=1&quot;&gt;
        ///    &lt;link rel=icon href=/favicon.ico&gt;
        ///    &lt;title&gt;sqlpal&lt;/title&gt;
        ///    &lt;link href=/main.css rel=preload as= style&gt;
        ///    &lt;link href=/vendor.css rel=preload as= style&gt;
        ///    &lt;link href=/app.js rel=preload as=script&gt;
        ///    &lt;link href=/vendor.js rel=preload as=script&gt;
        ///    &lt;link href=/vendor.css rel=stylesheet&gt;
        ///    &lt;link  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string index_html {
            get {
                return ResourceManager.GetString("index_html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select from where order group by insert update delete merge into having exec with declare create function procedure return returns begin end as if while for set try catch drop table view union all case then when cross apply outer inner left join and or on else raiserror throw tran commit rollback pivot unpivot for cursor open is in not null over partition using values varchar tinyint integer int bigint sysname date datetime datetime2 bit numeric char decimal varbinary execute fetch nvarchar revert nocount e [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string keywords1 {
            get {
                return ResourceManager.GetString("keywords1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sum avg min max count row_number rank isnull coalesce nullif getdate getutcdate getdate day month year len trim stuff datepart eomonth suser_sname cast convert db_name dateadd datediff.
        /// </summary>
        internal static string keywords2 {
            get {
                return ResourceManager.GetString("keywords2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #objectNavigator[data-v-725f895e]{float:left;width:25%;height:800px;overflow:auto;background:#f8f8f8;padding:20px}#textCtrl[data-v-725f895e]{float:left;padding:20px;width:70%;height:800px;overflow:auto;background-color:#fff}#connectionString[data-v-725f895e]{color:purple;font-size:small}#currentObjName[data-v-725f895e]{color:red;font-size:small}section[data-v-725f895e]:after{content:&quot;&quot;;display:table;clear:both}#objectList[data-v-725f895e]{width:250px;list-style-type:none;padding:0;padding-left:3px}#database [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string main_css {
            get {
                return ResourceManager.GetString("main_css", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to obj.
        /// </summary>
        internal static string objectNameParam {
            get {
                return ResourceManager.GetString("objectNameParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;pre id=&apos;text&apos; ng-bind-html=&apos;objectText&apos;&gt;&lt;/pre&gt;.
        /// </summary>
        internal static string objectText_html {
            get {
                return ResourceManager.GetString("objectText_html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to function openModal() {
        ///    //var overlay = document.getElementById(&apos;overlay&apos;);
        ///    //overlay.classList.remove(&quot;is-hidden&quot;);
        ///}
        ///
        ///function closeModal() {
        ///    //var overlay = document.getElementById(&apos;overlay&apos;);
        ///    //overlay.classList.add(&quot;is-hidden&quot;);
        ///}
        ///
        ///function getServerVal() {
        ///    var e = document.getElementById(&quot;serverSelect&quot;);
        ///    return e.options[e.selectedIndex].value;
        ///}
        ///
        ///function selectAllText(containerid) {
        ///    var range;
        ///    if (document.selection) {
        ///        range = document.body.createTextRange();
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string postConnectionString_js {
            get {
                return ResourceManager.GetString("postConnectionString_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prov1
        ///John Doe
        ///Somewhere
        ///.
        /// </summary>
        internal static string Prov_txt {
            get {
                return ResourceManager.GetString("Prov_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select A.name, schema_name = B.name, A.type_desc
        ///  from sys.objects A
        ///  left join sys.schemas B on A.schema_id = B.schema_id
        /// where type = @type
        /// order by type_desc, name;.
        /// </summary>
        internal static string queryAllObjects_sql {
            get {
                return ResourceManager.GetString("queryAllObjects_sql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select name 
        ///  from sys.databases 
        /// order by name.
        /// </summary>
        internal static string queryDatabaseList_sql {
            get {
                return ResourceManager.GetString("queryDatabaseList_sql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT *, num = row_number() over (partition by referenced_entity_name order by schema_name) 
        ///FROM (
        ///    SELECT DISTINCT 
        ///	       A.referenced_entity_name,
        ///		   B.type_desc,
        ///		   C.base_object_name,
        ///		   D.name AS schema_name
        ///    FROM sys.dm_sql_referenced_entities(@objectFullName, &apos;OBJECT&apos;) A
        ///    LEFT JOIN sys.objects B ON A.referenced_id = B.object_id
        ///	LEFT JOIN sys.synonyms C ON B.object_id = C.object_id
        ///   INNER JOIN sys.schemas D on isnull(B.schema_id, C.schema_id) = D.schema_id
        ///   WHERE A.referenced_i [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string queryObjectDependancies_sql {
            get {
                return ResourceManager.GetString("queryObjectDependancies_sql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT object_text = B.definition,
        ///       C.name,
        ///	   schema_name = A.name,
        ///	   A.type_desc
        ///FROM sys.objects A
        /// LEFT JOIN sys.sql_modules B ON A.object_id = B.object_id
        ///INNER JOIN sys.schemas C ON A.schema_id = C.schema_id
        ///WHERE A.name = @objectName
        ///  AND C.name = @schemaName;.
        /// </summary>
        internal static string queryObjectInfo_sql {
            get {
                return ResourceManager.GetString("queryObjectInfo_sql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  select distinct type, type_desc 
        ///   from sys.objects
        ///  where type in (&apos;P&apos;, &apos;TF&apos;, &apos;IF&apos;, &apos;FN&apos;, &apos;V&apos;, &apos;U&apos;);.
        /// </summary>
        internal static string queryObjectTypes_sql {
            get {
                return ResourceManager.GetString("queryObjectTypes_sql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT  row_number() OVER (ORDER BY [column].column_id) as &apos;@columnOrder&apos;,
        ///        [column].name AS &apos;@columnName&apos;,
        ///		[type].name AS &apos;@typeName&apos;, 
        ///		[type].max_length AS &apos;@maxLength&apos;,
        ///		[type].precision AS &apos;@precision&apos;,
        ///		case [column].is_nullable when 1 then &apos;Yes&apos; when 0 then &apos;No&apos; end AS &apos;@is_nullable&apos;,
        ///		case [column].is_identity when 1 then &apos;Yes&apos; when 0 then &apos;No&apos; end AS &apos;@is_identity&apos;
        ///	FROM sys.tables [table]
        ///	INNER JOIN sys.columns [column] ON [table].object_id = [column].object_id
        ///	INNER JOIN sys.types  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string queryTableXml_sql {
            get {
                return ResourceManager.GetString("queryTableXml_sql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sch.
        /// </summary>
        internal static string schemaNameParam {
            get {
                return ResourceManager.GetString("schemaNameParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;xsl:stylesheet version=&quot;1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot;
        ///    xmlns:msxsl=&quot;urn:schemas-microsoft-com:xslt&quot; exclude-result-prefixes=&quot;msxsl&quot;&gt;
        ///    &lt;xsl:output method=&quot;xml&quot; indent=&quot;yes&quot;/&gt;  
        ///    &lt;xsl:template match=&quot;/&quot;&gt;
        ///      &lt;table&gt;
        ///        &lt;tr&gt;
        ///          &lt;th&gt;№&lt;/th&gt;
        ///          &lt;th&gt;Column Name&lt;/th&gt;
        ///          &lt;th&gt;Type Name&lt;/th&gt;
        ///          &lt;th&gt;Max Length&lt;/th&gt;
        ///          &lt;th&gt;Precision&lt;/th&gt;
        ///          &lt;th&gt;Is nullable&lt;/th&gt;
        ///          &lt;th&gt;Is identity&lt;/th&gt;
        ///         [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string table2html_xslt {
            get {
                return ResourceManager.GetString("table2html_xslt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*!
        /// * Bootstrap v4.3.1 (https://getbootstrap.com/)
        /// * Copyright 2011-2019 The Bootstrap Authors
        /// * Copyright 2011-2019 Twitter, Inc.
        /// * Licensed under MIT (https://github.com/twbs/bootstrap/blob/master/LICENSE)
        /// */:root{--blue:#007bff;--indigo:#6610f2;--purple:#6f42c1;--pink:#e83e8c;--red:#dc3545;--orange:#fd7e14;--yellow:#ffc107;--green:#28a745;--teal:#20c997;--cyan:#17a2b8;--white:#fff;--gray:#6c757d;--gray-dark:#343a40;--primary:#007bff;--secondary:#6c757d;--success:#28a745;--info:#17a2b8;--warning:#ffc [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string vendor_css {
            get {
                return ResourceManager.GetString("vendor_css", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to (window[&quot;webpackJsonp&quot;]=window[&quot;webpackJsonp&quot;]||[]).push([[&quot;chunk-vendors&quot;],{&quot;01f9&quot;:function(t,e,n){&quot;use strict&quot;;var r=n(&quot;2d00&quot;),i=n(&quot;5ca1&quot;),o=n(&quot;2aba&quot;),a=n(&quot;32e9&quot;),s=n(&quot;84f2&quot;),l=n(&quot;41a0&quot;),u=n(&quot;7f20&quot;),c=n(&quot;38fd&quot;),f=n(&quot;2b4c&quot;)(&quot;iterator&quot;),d=!([].keys&amp;&amp;&quot;next&quot;in[].keys()),p=&quot;@@iterator&quot;,h=&quot;keys&quot;,v=&quot;values&quot;,b=function(){return this};t.exports=function(t,e,n,m,g,y,w){l(n,e,m);var O,S,P,T=function(t){if(!d&amp;&amp;t in j)return j[t];switch(t){case h:return function(){return new n(this,t)};case v:return function(){return  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string vendor_js {
            get {
                return ResourceManager.GetString("vendor_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;version&quot;:3,&quot;sources&quot;:[&quot;webpack:///./node_modules/core-js/modules/_iter-define.js&quot;,&quot;webpack:///./node_modules/core-js/modules/_string-at.js&quot;,&quot;webpack:///./node_modules/core-js/modules/_advance-string-index.js&quot;,&quot;webpack:///./node_modules/core-js/modules/es7.promise.finally.js&quot;,&quot;webpack:///./node_modules/axios/lib/core/Axios.js&quot;,&quot;webpack:///./node_modules/core-js/modules/_flags.js&quot;,&quot;webpack:///./node_modules/core-js/modules/_object-keys.js&quot;,&quot;webpack:///./node_modules/axios/lib/helpers/spread.js&quot;,&quot;webpack:/// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string vendor_map {
            get {
                return ResourceManager.GetString("vendor_map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*!
        /// * Vue.js v2.6.10
        /// * (c) 2014-2019 Evan You
        /// * Released under the MIT License.
        /// */
        ///(function (global, factory) {
        ///  typeof exports === &apos;object&apos; &amp;&amp; typeof module !== &apos;undefined&apos; ? module.exports = factory() :
        ///  typeof define === &apos;function&apos; &amp;&amp; define.amd ? define(factory) :
        ///  (global = global || self, global.Vue = factory());
        ///}(this, function () { &apos;use strict&apos;;
        ///
        ///  /*  */
        ///
        ///  var emptyObject = Object.freeze({});
        ///
        ///  // These helpers produce better VM code in JS engines due to their
        ///  // explicitness and funct [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string vue_js {
            get {
                return ResourceManager.GetString("vue_js", resourceCulture);
            }
        }
    }
}
